"""empty message

Revision ID: 6612f536e821
Revises: 844373ec7b67
Create Date: 2023-06-20 11:29:10.651398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6612f536e821'
down_revision = '844373ec7b67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('book_author_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'author', ['author_id'], ['id'])
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('book_author_fkey', 'author', ['author'], ['id'])
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
