"""empty message

Revision ID: 844373ec7b67
Revises: 9424328d5ed3
Create Date: 2023-06-20 11:26:35.812553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '844373ec7b67'
down_revision = '9424328d5ed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'author', ['author'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('author')

    # ### end Alembic commands ###
